"""Initial migration

Revision ID: 095a14abdacd
Revises: 
Create Date: 2026-04-07 14:59:06.327473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '095a14abdacd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('birthday <= CURRENT_DATE', name='check_birthday_not_future'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_birthday'), 'authors', ['birthday'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('available_instances', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_instances >= 0', name='check_available_instances_not_negative'),
    sa.CheckConstraint('publication_date <= CURRENT_DATE', name='check_publication_date_not_future'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_publication_date'), 'books', ['publication_date'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('books_on_hand', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('authors_books',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_index(op.f('ix_authors_books_author_id'), 'authors_books', ['author_id'], unique=False)
    op.create_index(op.f('ix_authors_books_book_id'), 'authors_books', ['book_id'], unique=False)
    op.create_table('book_loans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('due_date >= issued_at::date', name='check_due_after_issue'),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= issued_at', name='check_returned_after_issued'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_loans_book_open', 'book_loans', ['book_id'], unique=False, postgresql_where=sa.text('returned_at IS NULL'))
    op.create_index('idx_book_loans_user_open', 'book_loans', ['user_id'], unique=False, postgresql_where=sa.text('returned_at IS NULL'))
    op.create_index(op.f('ix_book_loans_book_id'), 'book_loans', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_loans_due_date'), 'book_loans', ['due_date'], unique=False)
    op.create_index(op.f('ix_book_loans_issued_at'), 'book_loans', ['issued_at'], unique=False)
    op.create_index(op.f('ix_book_loans_returned_at'), 'book_loans', ['returned_at'], unique=False)
    op.create_index(op.f('ix_book_loans_user_id'), 'book_loans', ['user_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('expires_at > created_at', name='check_refresh_expires_after_created'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_sessions_user_active', 'refresh_sessions', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_revoked_at'), 'refresh_sessions', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_revoked_at'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_expires_at'), table_name='refresh_sessions')
    op.drop_index('idx_refresh_sessions_user_active', table_name='refresh_sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_book_loans_user_id'), table_name='book_loans')
    op.drop_index(op.f('ix_book_loans_returned_at'), table_name='book_loans')
    op.drop_index(op.f('ix_book_loans_issued_at'), table_name='book_loans')
    op.drop_index(op.f('ix_book_loans_due_date'), table_name='book_loans')
    op.drop_index(op.f('ix_book_loans_book_id'), table_name='book_loans')
    op.drop_index('idx_book_loans_user_open', table_name='book_loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_index('idx_book_loans_book_open', table_name='book_loans', postgresql_where=sa.text('returned_at IS NULL'))
    op.drop_table('book_loans')
    op.drop_index(op.f('ix_authors_books_book_id'), table_name='authors_books')
    op.drop_index(op.f('ix_authors_books_author_id'), table_name='authors_books')
    op.drop_table('authors_books')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_publication_date'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_birthday'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
